# Generated by Django 3.2.3 on 2023-05-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_news', '0002_alter_news_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('city', 'weather')},
        ),
    ]
